name: build 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: 'gradle'

    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Build And Test With Gradle Wrapper
      run: ./gradlew clean jacocoTestReport --info --stacktrace
    
    - name: Code Coverage Report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./build/reports/jacoco/test/jacocoTestReport.xml
        fail_ci_if_error: true
        verbose: true
